Add monitoring capabilities to Kafka straight out of the box
philips-labs/terraform-hsdp-zookeeper pull request #6
Opened 2021-01-06 11:08 UTC by rik-v

This change pulls in the JMX exporter directly to deploying zookeeper.

2021-01-06 11:54 UTC, loafoe requested changes

2021-01-06 11:54 UTC, loafoe commented on containter_host.tf
> +      "chmod 777 /home/${var.user}/jmxconfig.yml",
Why 777?

2021-01-28 08:27 UTC, johanhorst-at-philips commented on containter_host.tf
> +      "chmod 777 /home/${var.user}/jmxconfig.yml",
Changed to 755, no reason ;-)

2021-01-28 09:00 UTC, loafoe commented on main.tf
> +  file {
This should be dynamic no?

2021-01-28 09:00 UTC, loafoe commented on main.tf
> +    source      = "${path.module}/scripts/jmxconfig.yml.tmpl"
And is it a template with requires variable subtitutions? or just a static .yml?

2021-01-28 09:02 UTC, johanhorst-at-philips commented on main.tf
> +    source      = "${path.module}/scripts/jmxconfig.yml.tmpl"
There is one variable that is substituted.

2021-01-28 09:10 UTC, loafoe commented on main.tf
> +    source      = "${path.module}/scripts/jmxconfig.yml.tmpl"
BTW, this module resolves variables in a script on the server. This was before I learned about `templatefile` which can render the template on the Terraform and basically just push parameterless scripts to the server.  Some day we should rewrite this :)

2021-01-28 09:12 UTC, merged

2021-01-28 09:13 UTC, johanhorst-at-philips commented on main.tf
> +  file {
as discussed, it is nice, but not necessary